### ISSUE TITLE
vllm Model architectures不支持问题

### ISSUE THREAD

**Issue by xiaochake** [liunian-Jay/MU-GOT#3]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/chuzuowei/chem/Vary-main/MU-GOT/pdf2txt.py", line 1, in <module>
[rank0]:     from PDF_parsing import pdf2md, vllm_got, process_md
[rank0]:   File "/data/chuzuowei/chem/Vary-main/MU-GOT/PDF_parsing/__init__.py", line 65, in <module>
[rank0]:     model, tokenizer, image_processor, image_processor_high = init_model_GOT()
[rank0]:   File "/data/chuzuowei/chem/Vary-main/MU-GOT/PDF_parsing/__init__.py", line 31, in init_model_GOT
[rank0]:     model = LLM(model=model_name, max_model_len=8192, trust_remote_code=True)
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 155, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 441, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 251, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 36, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/worker/worker.py", line 139, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 682, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 280, in load_model
[rank0]:     model = _initialize_model(model_config, self.load_config,
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 108, in _initialize_model
[rank0]:     model_class = get_model_architecture(model_config)[0]
[rank0]:   File "/data/chuzuowei/anaconda3/envs/MU_GOT/lib/python3.10/site-packages/vllm/model_executor/model_loader/utils.py", line 36, in get_model_architecture
[rank0]:     raise ValueError(
[rank0]: ValueError: Model architectures ['GOTQwenForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChameleonForCausalLM', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'FalconForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PaliGemmaForConditionalGeneration', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3VForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MedusaModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'MistralModel']

**Comment by liunian-Jay** [comment]
文件PDF_parsing/__init__.py，其中有如下几行代码，它的作用是把Qwen2GotForCausalLM注册。
```
from vllm import LLM, ModelRegistry
from GOT.model import Qwen2GotForCausalLM
# from GOT.model import GOTQwenForCausalLM # 无vllm加速原版
ModelRegistry.register_model("Qwen2GotForCausalLM", Qwen2GotForCausalLM)
```

另外，“ValueError: Model architectures ['GOTQwenForCausalLM'] are not supported for now”  应该是因为这里使用的模型是重写了名字的GOTQwenForCausalLM，所以模型权重目录中的config中的模型名称需要修改成Qwen2GotForCausalLM
